spring:
  application:
    name: 'order-service-api'
  profiles:
    active: ${PROFILE_ACTIVE}
  cloud:
    config:
      name: 'order-service-api'
      uri: 'config-server'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT:10000}